/**
 * Preset del Design System (CJS para require() en apps).
 * Uso: presets: [require('@kuspit/design-system/tailwind.config.cjs')]
 */

module.exports = {
  content: [],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: "var(--card)",
        "card-foreground": "var(--card-foreground)",
        popover: "var(--popover)",
        "popover-foreground": "var(--popover-foreground)",
        primary: "var(--primary)",
        "primary-foreground": "var(--primary-foreground)",
        "primary-dark": "var(--primary-dark)",
        "primary-light": "var(--primary-light)",
        "primary-light-foreground": "var(--primary-light-foreground)",
        "primary-lighter": "var(--primary-lighter)",
        secondary: "var(--secondary)",
        "secondary-foreground": "var(--secondary-foreground)",
        muted: "var(--muted)",
        "muted-foreground": "var(--muted-foreground)",
        accent: "var(--accent)",
        "accent-foreground": "var(--accent-foreground)",
        "menu-accent": "var(--menu-accent)",
        "menu-accent-foreground": "var(--menu-accent-foreground)",
        destructive: "var(--destructive)",
        "destructive-foreground": "var(--destructive-foreground)",
        "destructive-background": "var(--destructive-background)",
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        disabled: "var(--disabled)",
        "disabled-background": "var(--disabled-background)",
        "input-text": "var(--input-text)",
        "success-light": "var(--success-light)",
        "success-light-foreground": "var(--success-light-foreground)",
        info: "var(--info)",
        "info-foreground": "var(--info-foreground)",
        "status-primary": "var(--status-primary)",
        "status-success": "var(--status-success)",
        "status-yellow": "var(--status-yellow)",
        "status-warning": "var(--status-warning)",
        "status-danger": "var(--status-danger)",
        "status-blue": "var(--status-blue)",
        "neutral-500": "var(--neutral-500)",
        "error-light": "var(--error-light)",
        sidebar: "var(--sidebar)",
        "sidebar-foreground": "var(--sidebar-foreground)",
        "sidebar-primary": "var(--sidebar-primary)",
        "sidebar-primary-foreground": "var(--sidebar-primary-foreground)",
        "sidebar-accent": "var(--sidebar-accent)",
        "sidebar-accent-foreground": "var(--sidebar-accent-foreground)",
        "sidebar-border": "var(--sidebar-border)",
        "sidebar-ring": "var(--sidebar-ring)",
        chart: {
          1: "var(--chart-1)",
          2: "var(--chart-2)",
          3: "var(--chart-3)",
          4: "var(--chart-4)",
          5: "var(--chart-5)",
        },
      },
      borderRadius: {
        sm: "calc(var(--radius) - 4px)",
        md: "calc(var(--radius) - 2px)",
        lg: "var(--radius)",
        xl: "calc(var(--radius) + 4px)",
      },
      fontFamily: {
        sans: ["var(--font-sans)", "sans-serif"],
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        default: "1px 2px 4px 0px hsla(0, 0%, 0%, 0.05)",
        "default-hover": "0px 4px 6px 0px hsla(0, 0%, 0%, 0.1)",
        warning: "0px 4px 6px 0px hsla(17, 79%, 54%, 0.1)",
        "warning-hover": "4px 6px 6px 0px hsla(17, 79%, 54%, 0.15)",
        danger: "4px 6px 6px 0px hsla(0, 85%, 49%, 0.1)",
        "danger-hover": "4px 6px 6px 0px hsla(0, 85%, 49%, 0.15)",
        "default-card": "0px 4px 6px 0px hsla(0, 0%, 0%, 0.1)",
      },
    },
  },
  plugins: [],
};
